database:
  host: localhost
  port: 5432
  name: p2p_bot
  user: antonmiklis
  password: ${DB_PASSWORD}
  ssl: disable
redis:
  host: localhost
  port: 6479
  db: 0
rabbitmq:
  url: amqp://guest:guest@localhost/
telegram:
  api-key: ${BOT_TOKEN}
  bot-link: t.me/p2pmonitor_bot
exchange:
  max-retries: 20
  retry-delay: 30
website:
  port: 1323
  jwt-secret: ${JWT_SECRET}
