services:
  mini-app:
    build:
      context: tg-mini-app
      dockerfile: production.Dockerfile
    volumes:
      - react-app:/app/dist
  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: ./certs
        target: /etc/nginx/certs
        read_only: true
      - type: volume
        source: react-app
        target: /var/www/html
      - type: bind
        source: ./nginx/prod.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    depends_on:
      - web-server
      - mini-app
    networks:
      - app-network
  tg-bot:
    build:
      context: ./cmd/p2pbot
    volumes:
      - ./.env:/app/.env
      - ./config.yaml:/app/config.yaml
      - ./internal/db/migrations:/app/internal/db/migrations
    depends_on:
      - db
      - rabbitmq
      - cache
    networks:
      - app-network

  web-server:
    build:
      context: ./cmd/server
    volumes:
      - ./.env:/app/.env
      - ./config.yaml:/app/config.yaml
      - ./internal/db/migrations:/app/internal/db/migrations
      - ./certs:/app/certs
    depends_on:
      - db
      - rabbitmq
      - cache
    networks:
      - app-network

  observer:
    build:
      context: ./cmd/observer
    volumes:
      - ./.env:/app/.env
      - ./config.yaml:/app/config.yaml
      - ./internal/db/migrations:/app/internal/db/migrations
    depends_on:
      - db
      - rabbitmq
      - cache
    networks:
      - app-network

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: antonmiklis
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: p2p_bot
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network
  cache:
    image: redis/redis-stack
    networks:
      - app-network
  rabbitmq:
    image: rabbitmq:management
    networks:
      - app-network

volumes:
  db_data:
  react-app:

networks:
  app-network:
    external: true
