services:
  tg-bot:
    build:
      context: ./cmd/p2pbot
    volumes:
      - ./.env:/app/.env
      - ./config.yaml:/app/config.yaml
      - ./internal/db/migrations:/app/internal/db/migrations
    depends_on:
      - db
      - rabbitmq
      - cache
    networks:
      - app-network

  web-server:
    build:
      context: ./cmd/server
    ports:
      - "443:443"
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./.env:/app/.env
      - ./config.yaml:/app/config.yaml
      - ./internal/db/migrations:/app/internal/db/migrations
      - ./certs:/app/certs
    depends_on:
      - db
      - rabbitmq
      - cache
    networks:
      - app-network

  observer:
    build:
      context: ./cmd/observer
    volumes:
      - ./.env:/app/.env
      - ./config.yaml:/app/config.yaml
      - ./internal/db/migrations:/app/internal/db/migrations
    depends_on:
      - db
      - rabbitmq
      - cache
    networks:
      - app-network

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: antonmiklis
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: p2p_bot
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
  cache:
    image: redis/redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - app-network
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    external: true
